name: Release

on:
  push:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

permissions: {}

jobs:
  # ci:
  #   name: CI
  #   permissions:
  #     contents: read
  #   uses: ./.github/workflows/ci.yml

  release:
    # prevent this action from running on forks
    if: github.repository == 'code-alexander/spacecake'
    name: Release
    runs-on: macos-latest
    # needs: [ci]

    timeout-minutes: 30
    defaults:
      run:
        working-directory: ./spacecake-app

    permissions:
      contents: write
      id-token: write
      pull-requests: write

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Set up pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 8

      - name: Install dependencies
        run: pnpm install

      # - name: Load certificates (macOS)
      #   env:
      #     MACOS_CERT_P12: ${{ secrets.CSC_CONTENT }}
      #     MACOS_CERT_PASSWORD: ${{ secrets.CSC_KEY_PASSWORD }}
      #   run: chmod +x scripts/add-macos-cert.sh && . ./scripts/add-macos-cert.sh

      - name: Load certificates (macOS)
        uses: apple-actions/import-codesign-certs@v3
        with:
          p12-file-base64: ${{ secrets.CSC_CONTENT }}
          p12-password: ${{ secrets.CSC_KEY_PASSWORD }}

      # use v1.5.1
      # https://github.com/changesets/action/issues/501
      - name: Create Release Pull Request or Publish
        uses: changesets/action@v1.5.1
        with:
          cwd: ./spacecake-app
          publish: bash scripts/publish-release.sh
        env:
          # changesets action uses this for PR creation
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # wrapper script uses this to override GITHUB_TOKEN for electron-forge
          PUBLIC_REPO_ACCESS_TOKEN: ${{ secrets.PUBLIC_REPO_ACCESS_TOKEN }}
          # Credentials for Apple Notarization
          APPLE_ID: ${{ secrets.APPLE_ID }}
          APPLE_PASSWORD: ${{ secrets.APPLE_PASSWORD }}
          APPLE_TEAM_ID: ${{ secrets.APPLE_TEAM_ID }}
          APPLE_SIGN_ID: ${{ secrets.APPLE_SIGN_ID }}
